// TO DO LIST :
// - RANDOM TIME TO GENERATE OBSTACLES
// - AJOUTER UN SON DE GAME OVER
// - FAIRE AVANCER LE TERRAIN QUAND ISPLAYING = TRUE
// - FAIRE AVANCER LES ÉTOILES PLUS VITE QUAND ISPLAYING = TRUE
// - UTILISER UN COMPONENT OBSTACLE PLUTÔT QUE DE CRÉER DIV + CLASSNAME + ...
// - ÉCRIRE README EN ANGLAIS
// - GÉRER ON/OFF DES BRUITAGES
// - AFFICHER SCORE SOUS UNE NOUVELLE FORME ET CENTRÉ : 000000 > 000345
// - FAIRE LA PAGE "NO MATCH"
// - MODE DE JEU MOBILE AVEC UN BOUTON "UP"

// - RANDOM TIME TO GENERATE OBSTACLES
// const min = 1500; // s
// const max = 5000; // s
// const randomTime = Math.floor(Math.random() * (max - min + 1) + min);
