// TO DO LIST :
// - /!\ IMPORTANT /!\ RANDOM TIME TO GENERATE OBSTACLES
// - FAIRE AVANCER LE TERRAIN QUAND ISPLAYING = TRUE
// - FAIRE AVANCER LES ÉTOILES PLUS VITE QUAND ISPLAYING = TRUE
// - UTILISER UN COMPONENT OBSTACLE PLUTÔT QUE DE CRÉER DIV + CLASSNAME + ...
// - ÉCRIRE README EN ANGLAIS
// - AFFICHER SCORE SOUS UNE NOUVELLE FORME ET CENTRÉ : 000000 > 000345
// - FAIRE LA PAGE "NO MATCH"
// - MODE DE JEU MOBILE AVEC UN BOUTON "UP"
// - DÉCLANCHER MUSIC SI C'EST TRUE EN LOCAL STORAGE ET SI ON REFRESH

// - RANDOM TIME TO GENERATE OBSTACLES
// const min = 1500; // s
// const max = 5000; // s
// const randomTime = Math.floor(Math.random() * (max - min + 1) + min);
